"""Read the decoded corpus CSVs and render typed SQL seed values."""

from __future__ import annotations

import csv
import math
from dataclasses import dataclass
from pathlib import Path
from typing import Iterator


@dataclass
class CsvHeader:
    column_indices: list[str]
    column_types: list[str]


@dataclass
class CsvRow:
    row_id: str
    values: list[str]


def read_csv(path: Path) -> tuple[CsvHeader, Iterator[CsvRow]]:
    """Open a corpus CSV and return its header plus a lazy row iterator."""
    handle = path.open("r", encoding="utf-8", newline="")
    try:
        reader = csv.reader(handle)
        label_row = next(reader)
        type_row = next(reader)
    except StopIteration:
        handle.close()
        raise ValueError(
            f"{path}: missing label/type header rows (need at least 2 lines)"
        ) from None
    except BaseException:
        handle.close()
        raise

    header = CsvHeader(
        column_indices=label_row[1:],
        column_types=type_row[1:],
    )

    def iter_rows() -> Iterator[CsvRow]:
        try:
            for row in reader:
                if not row:
                    continue
                yield CsvRow(row_id=row[0], values=row[1:])
        finally:
            handle.close()

    return header, iter_rows()


def sql_int(value: str) -> str:
    """Coerce a CSV integer value to a canonical SQL literal. Empty is 0."""
    if value == "":
        return "0"
    return str(int(value))


# Bounds-check typed integers so bad corpus values fail before SQL generation.
_INT_BOUNDS = {
    "s8": (-128, 127),
    "u8": (0, 255),
    "s16": (-32768, 32767),
    "u16": (0, 65535),
    "s32": (-2147483648, 2147483647),
    "u32": (0, 4294967295),
}


def _make_int_coercer(lo: int, hi: int):
    def coercer(value: str) -> str:
        if value == "":
            return "0"
        n = int(value)
        if not lo <= n <= hi:
            raise ValueError(f"integer {n} out of range [{lo}, {hi}]")
        return str(n)

    return coercer


def sql_bool(value: str) -> str:
    """Coerce a CSV boolean value to 0 or 1. Empty values become 0."""
    low = value.lower()
    if value == "" or low == "false":
        return "0"
    if low == "true":
        return "1"
    return "1" if int(value) != 0 else "0"


def sql_float(value: str) -> str:
    """Coerce a CSV float value to a SQL float literal. Empty -> 0."""
    if value == "":
        return "0"
    f = float(value)
    if math.isinf(f) or math.isnan(f):
        raise ValueError(f"non-finite float {value!r} is not a valid SQL literal")
    return repr(f)


def sql_string(value: str) -> str:
    """Quote a CSV string for SQL. Empty -> empty string literal."""
    escaped = value.replace("\\", "\\\\").replace("'", "''")
    return f"'{escaped}'"


COERCERS = {
    "s8": _make_int_coercer(*_INT_BOUNDS["s8"]),
    "u8": _make_int_coercer(*_INT_BOUNDS["u8"]),
    "s16": _make_int_coercer(*_INT_BOUNDS["s16"]),
    "u16": _make_int_coercer(*_INT_BOUNDS["u16"]),
    "s32": _make_int_coercer(*_INT_BOUNDS["s32"]),
    "u32": _make_int_coercer(*_INT_BOUNDS["u32"]),
    "bool": sql_bool,
    "float": sql_float,
    "str": sql_string,
}


def _validate_column_indices(columns: list, width: int, source_csv: str) -> None:
    """Raise if a declared integer CSV column index exceeds the header width."""
    for col in columns:
        source = col[1]
        if isinstance(source, int) and source >= width:
            raise ValueError(
                f"{source_csv}: column index {source} for {col[0]!r} exceeds "
                f"header width {width}"
            )


def coerce(value: str, type_hint: str) -> str:
    """Coerce a raw CSV value to a SQL literal using a CSV type hint."""
    coercer = COERCERS.get(type_hint)
    if coercer is None:
        raise ValueError(f"unknown CSV type hint: {type_hint!r}")
    return coercer(value)


def _const_literal(source: str, csv_type: str) -> str:
    """Resolve a ``const:N`` column source to its typed SQL literal."""
    literal = source[len("const:"):]
    if literal == "NULL":
        return "NULL"
    return coerce(literal, csv_type)


ColumnSpec = tuple[str, object, str]


SEED_MARKER = "-- Generated by xivl-client-data/tools/csv_to_sql.py"


def _write_seed_file(out_path: Path, seed_content: str) -> None:
    """Write a complete seed fragment with its marker, sources, and INSERTs."""
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", encoding="utf-8", newline="\n") as f:
        f.write(seed_content)


def write_single_csv_seed(
    sql_table: str,
    source_csv: str,
    columns: list[ColumnSpec],
    csv_dir: Path,
    out_dir: Path,
) -> Path:
    """Generate one seed fragment from a single CSV source and column mapping."""
    csv_path = csv_dir / source_csv
    header, rows = read_csv(csv_path)
    _validate_column_indices(columns, len(header.column_indices), source_csv)

    inserts: list[str] = []
    row_count = 0
    for row in rows:
        row_count += 1
        values: list[str] = []
        for _output_col, source, csv_type in columns:
            if source == "row_id":
                values.append(sql_int(row.row_id))
            elif isinstance(source, str) and source.startswith("const:"):
                values.append(_const_literal(source, csv_type))
            else:
                position = int(source)  # type: ignore[arg-type]
                raw = row.values[position] if position < len(row.values) else ""
                values.append(coerce(raw, csv_type))
        inserts.append(f"INSERT INTO {sql_table} VALUES ({', '.join(values)});")

    out_path = out_dir / f"{sql_table}.sql"
    seed_content = (
        _seed_header(source_csv)
        + "\n"
        + "\n".join(inserts)
        + "\n"
    )
    _write_seed_file(out_path, seed_content)
    return out_path


def _seed_header(source_csv: str) -> str:
    return "\n".join([
        SEED_MARKER,
        f"-- Source: xivl-client-data/csv/{source_csv}",
        "",
    ])


MultiColumnSpec = tuple[str, object, object, str]  # (output_col, csv_filename_or_None, source, csv_type)


def write_multi_csv_seed(
    sql_table: str,
    sources: list[str],
    columns: list[MultiColumnSpec],
    csv_dir: Path,
    out_dir: Path,
    join_keys: dict[str, tuple[str, int]] | None = None,
    require_join_match: bool = True,
) -> Path:
    """Generate a joined seed under the contract in tools/README.md."""
    sources_data: dict[str, dict[str, CsvRow]] = {}
    source_widths: dict[str, int] = {}
    for csv_filename in sources:
        csv_path = csv_dir / csv_filename
        header, rows = read_csv(csv_path)
        source_widths[csv_filename] = len(header.column_indices)
        indexed: dict[str, CsvRow] = {}
        for row in rows:
            if row.row_id in indexed:
                raise ValueError(
                    f"{csv_filename}: duplicate row_id {row.row_id!r}; "
                    f"merge would silently drop a row"
                )
            indexed[row.row_id] = row
        sources_data[csv_filename] = indexed

    for output_col, csv_filename, source, _csv_type in columns:
        if (
            isinstance(source, int)
            and csv_filename in source_widths
            and source >= source_widths[csv_filename]
        ):
            raise ValueError(
                f"{csv_filename}: column index {source} for {output_col!r} "
                f"exceeds header width {source_widths[csv_filename]}"
            )

    driver = sources[0]
    join_keys = join_keys or {}

    inserts: list[str] = []
    row_count = 0
    for iteration_index, row_id in enumerate(sources_data[driver]):
        row_count += 1
        values: list[str] = []
        for _output_col, csv_filename, source, csv_type in columns:
            if source == "iteration_index":
                values.append(str(iteration_index))
                continue
            if isinstance(source, str) and source.startswith("const:"):
                values.append(_const_literal(source, csv_type))
                continue
            if callable(source):
                resolved = source(row_id, sources_data)
                values.append("NULL" if resolved is None else coerce(resolved, csv_type))
                continue
            if csv_filename not in sources_data:
                raise ValueError(f"column references unknown source: {csv_filename!r}")
            if csv_filename in join_keys:
                join_csv, join_col = join_keys[csv_filename]
                join_row = sources_data[join_csv].get(row_id)
                lookup_key = (
                    join_row.values[join_col]
                    if join_row and join_col < len(join_row.values)
                    else ""
                )
                row = sources_data[csv_filename].get(lookup_key)
                missing_key = lookup_key
            else:
                row = sources_data[csv_filename].get(row_id)
                missing_key = row_id
            if row is None:
                if require_join_match:
                    raise ValueError(
                        f"{sql_table}: no row in {csv_filename} for key "
                        f"{missing_key!r} (driver {driver} row {row_id!r}); set "
                        f"REQUIRE_JOIN_MATCH=False on the mapping if this join "
                        f"is intentionally partial"
                    )
                values.append(coerce("", csv_type))
            elif source == "row_id":
                values.append(sql_int(row.row_id))
            else:
                position = int(source)  # type: ignore[arg-type]
                raw = row.values[position] if position < len(row.values) else ""
                values.append(coerce(raw, csv_type))
        inserts.append(f"INSERT INTO {sql_table} VALUES ({', '.join(values)});")

    out_path = out_dir / f"{sql_table}.sql"
    seed_content = (
        _seed_header_multi(sources)
        + "\n"
        + "\n".join(inserts)
        + "\n"
    )
    _write_seed_file(out_path, seed_content)
    return out_path


def _seed_header_multi(sources: list[str]) -> str:
    source_lines = [f"-- Source: xivl-client-data/csv/{s}" for s in sources]
    return "\n".join([
        SEED_MARKER,
        *source_lines,
        "",
    ])
